<a href="https://colab.research.google.com/github/chetansolanke14/Tensorflow_DL/blob/master/California_Census_data_Classification_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [0]:
import pandas as pd

In [0]:
census =pd.read_csv('census_data.csv')

In [81]:
census.head()

age          workclass  ...  native_country  income_bracket
0   39          State-gov  ...   United-States               0
1   50   Self-emp-not-inc  ...   United-States               0
2   38            Private  ...   United-States               0
3   53            Private  ...   United-States               0
4   28            Private  ...            Cuba               0

[5 rows x 14 columns]

In [83]:
census['occupation'].count()

32561

In [85]:
census.describe()

age  education_num  ...  hours_per_week  income_bracket
count  32561.000000   32561.000000  ...    32561.000000    32561.000000
mean      38.581647      10.080679  ...       40.437456        0.240810
std       13.640433       2.572720  ...       12.347429        0.427581
min       17.000000       1.000000  ...        1.000000        0.000000
25%       28.000000       9.000000  ...       40.000000        0.000000
50%       37.000000      10.000000  ...       40.000000        0.000000
75%       48.000000      12.000000  ...       45.000000        0.000000
max       90.000000      16.000000  ...       99.000000        1.000000

[8 rows x 6 columns]

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [5]:
census.dtypes

age                int64
workclass         object
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
gender            object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income_bracket    object
dtype: object

In [10]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

array([' <=50K', ' >50K'], dtype=object)

In [0]:
def label_fix(label):
    if label==' <=50K':
        return 0
    else:
        return 1

In [0]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

In [0]:
x_data =census.drop('income_bracket', axis=1)
y_val = census['income_bracket']

In [0]:
# Cool Alternative
# lambda label:int(label==' <=50k')

# census['income_bracket'].apply(lambda label: int(label==' <=50K'))

### Perform a Train Test Split on the Data

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [33]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [0]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [0]:
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ["Female", "Male"])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [0]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

** Put all these variables into a single list with the variable name feat_cols **

In [0]:
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
            age,education_num,capital_gain,capital_loss,hours_per_week]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [0]:
input_func=tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train, batch_size=128, num_epochs=2000, shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [39]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpyulzirlx', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fd088451e80>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


** Train your model on the data, for at least 5000 steps. **

In [40]:
model.train(input_fn=input_func,steps =5000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpyulzirlx/model.ckpt.
INFO:tensorflow:loss = 88.722855, step = 1
INFO:tensorflow:global_step/sec: 127.781
INFO:tensorflow:loss = 209.86865, step = 101 (0.787 sec)
INFO:tensorflow:global_step/sec: 192.712
INFO:tensorflow:loss = 298.25708, step = 201 (0.522 sec)
INFO:tensorflow:global_step/sec:

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [0]:
pred_input_func =tf.estimator.inputs.pandas_input_fn(X_test,batch_size =100, num_epochs=1,shuffle=False)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [50]:
#pred_gen =model.predict(pred_input_func)
predictions = list(model.predict(input_fn=pred_input_func))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpyulzirlx/model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [55]:
predictions[1]['class_ids'][0]

0

In [0]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['class_ids'][0])

** Each item in your list will look like this: **

In [57]:
predictions[1]

{'class_ids': array([0]),
 'classes': array([b'0'], dtype=object),
 'logistic': array([3.3676624e-05], dtype=float32),
 'logits': array([-10.299018], dtype=float32),
 'probabilities': array([9.9996638e-01, 3.3665012e-05], dtype=float32)}

In [59]:
final_preds[:10]

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [0]:
from sklearn.metrics import confusion_matrix,f1_score,roc_curve,accuracy_score,classification_report

In [61]:
confusion_matrix(y_test,final_preds)

array([[6869,  567],
       [1149, 1184]])

In [65]:
f1_score(y_test,final_preds)

0.5798237022526934

In [67]:
accuracy_score(y_test,final_preds)

0.8243423072985976

In [68]:
roc_curve(y_test,final_preds)

(array([0.        , 0.07625067, 1.        ]),
 array([0.        , 0.50750107, 1.        ]),
 array([2, 1, 0]))

In [71]:
print(classification_report(y_test,final_preds))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89      7436
           1       0.68      0.51      0.58      2333

   micro avg       0.82      0.82      0.82      9769
   macro avg       0.77      0.72      0.73      9769
weighted avg       0.81      0.82      0.82      9769



# Great Job!